theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: technorealisme.org
  breadcrumb:
    position: hero-start
  summary:
    position: hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/icon-color.svg"
  pages:
    index:
      truncate_description: 0
  posts:
    index:
      truncate_description: 0
      layout: grid
      options:
        hide_author: false
