[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/outil/"
to = "/manifeste/mode-ia/ia-outil/"

[[redirects]]
from = "/equipe/christelle-serou/"
to = "/think-tank/membres/christelle-serou/"

[[redirects]]
from = "/equipe/eric-boillaud/"
to = "/think-tank/membres/eric-boillaud/"

[[redirects]]
from = "/manifeste/dix-lecons-ia/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/lia-comme-outil-lillusion-du-controle/"
to = "/manifeste/mode-ia/ia-outil/"

[[redirects]]
from = "/technorealistes/dylan-thomas/"
to = "/think-tank/membres/dylan-thomas/"

[[redirects]]
from = "/principes/"
to = "/think-tank/principes/"

[[redirects]]
from = "/manifeste/meilleure-description/ecriture-de-son-propre-code/"
to = "/manifeste/description-ia/ia-code/"

[[redirects]]
from = "/membres/nour-trabelsi/"
to = "/think-tank/membres/nour-trabelsi/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/pour-une-meilleure-description-de-lia/lia-frugale/"
to = "/manifeste/description-ia/ia-energie/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/les-modeles-dia-lillusion-de-familiarite/"
to = "/manifeste/mode-ia/modeles-ia/"

[[redirects]]
from = "/manifeste/mode-ia/discours-tronques/"
to = "/manifeste/mode-ia/ia-amelioration/"

[[redirects]]
from = "/manifeste/meilleure-description/ia-code/"
to = "/manifeste/description-ia/ia-code/"

[[redirects]]
from = "/manifeste/meilleure-description/ia-data-1/"
to = "/manifeste/description-ia/ia-donnee/"

[[redirects]]
from = "/manifeste/meilleure-description/processus-metier/"
to = "/manifeste/description-ia/ia-programme/"

[[redirects]]
from = "/technorealistes/arnaud-levy/"
to = "/think-tank/membres/arnaud-levy/"

[[redirects]]
from = "/technorealistes/"
to = "/think-tank/membres/"

[[redirects]]
from = "/manifeste/meilleure-description/programme-ia/"
to = "/manifeste/description-ia/ia-programme/"

[[redirects]]
from = "/discussions/2023-12-08-nia-non-intelligence-artificielle-ou-la-rage-doffrir-des-couleurs-au-monde/"
to = "/articles/2023-12-08-nia-non-intelligence-artificielle-ou-la-rage-doffrir-des-couleurs-au-monde/"

[[redirects]]
from = "/manifeste/dix-lecons/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/autonome/"
to = "/manifeste/mode-ia/ia-autonome/"

[[redirects]]
from = "/think-tank/membres/dylan-thomas/actualites/"
to = "/think-tank/membres/dylan-thomas/articles/"

[[redirects]]
from = "/manifeste/pour-une-meilleure-description-de-lia/les-programmes-dia-dans-le-cadre-de-processus-metier/"
to = "/manifeste/description-ia/ia-programme/"

[[redirects]]
from = "/manifeste/a-lencontre-de-quelques-lubies-dominantes-sur-lia/"
to = "/manifeste/mode-ia/"

[[redirects]]
from = "/manifeste/mode-ia/decision-ia/"
to = "/manifeste/mode-ia/ia-decision/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/"
to = "/manifeste/mode-ia/"

[[redirects]]
from = "/manifeste/intelligence-artificielle-dix-lecons/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/think-tank/manifeste/mode-ia/"
to = "/manifeste/mode-ia/"

[[redirects]]
from = "/equipe/arnaud-billion/"
to = "/think-tank/membres/arnaud-billion/"

[[redirects]]
from = "/membres/arnaud-levy/"
to = "/think-tank/membres/arnaud-levy/"

[[redirects]]
from = "/think-tank/membres/martin-bole/"
to = "/think-tank/membres/martin-bolle/"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/modeles/"
to = "/manifeste/mode-ia/modeles-ia/"

[[redirects]]
from = "/manifeste/meilleure-description/ia-energie/"
to = "/manifeste/description-ia/ia-energie/"

[[redirects]]
from = "/equipe/malek-mammar/"
to = "/think-tank/membres/malek-mammar/"

[[redirects]]
from = "/membres/arnaud-billion/"
to = "/think-tank/membres/arnaud-billion/"

[[redirects]]
from = "/technorealistes/olivier-frerot/"
to = "/think-tank/membres/olivier-frerot/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/vers-une-ia-de-qualite/"
to = "/manifeste/ia-qualite/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/decision-ia/"
to = "/manifeste/mode-ia/ia-decision/"

[[redirects]]
from = "/technorealistes/antoine-moreau/"
to = "/think-tank/membres/antoine-moreau/"

[[redirects]]
from = "/editions/2024-lettres-de-la-machine-manuel-entree-sortie-ia/"
to = "/livres/2024-lettres-de-la-machine-manuel-entree-sortie-ia/"

[[redirects]]
from = "/equipe/flavien-volken/"
to = "/think-tank/membres/flavien-volken/"

[[redirects]]
from = "/introduction/"
to = "/think-tank/technorealisme/"

[[redirects]]
from = "/technorealistes/eric-boillaud/"
to = "/think-tank/membres/eric-boillaud/"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/systeme/"
to = "/manifeste/mode-ia/ia-systeme/"

[[redirects]]
from = "/manifeste/meilleure-description/ia-frugale/"
to = "/manifeste/description-ia/ia-energie/"

[[redirects]]
from = "/think-tank/manifeste/description-ia/"
to = "/manifeste/description-ia/"

[[redirects]]
from = "/equipe/anaelle-martin/"
to = "/think-tank/membres/anaelle-martin/"

[[redirects]]
from = "/discussions/2024-03-08-collection-imaginaires/"
to = "/articles/2024-03-08-collection-imaginaires/"

[[redirects]]
from = "/manifeste/lubies/"
to = "/manifeste/mode-ia/"

[[redirects]]
from = "/manifeste/meilleure-description/les-programmes-dia-dans-le-cadre-de-processus-metier/"
to = "/manifeste/description-ia/ia-programme/"

[[redirects]]
from = "/equipe/dylan-thomas/"
to = "/think-tank/membres/dylan-thomas/"

[[redirects]]
from = "/membres/antoine-moreau/"
to = "/think-tank/membres/antoine-moreau/"

[[redirects]]
from = "/actualites/2023-12-08-nia-non-intelligence-artificielle-ou-la-rage-doffrir-des-couleurs-au-monde/"
to = "/articles/2023-12-08-nia-non-intelligence-artificielle-ou-la-rage-doffrir-des-couleurs-au-monde/"

[[redirects]]
from = "/membres/eric-boillaud/"
to = "/think-tank/membres/eric-boillaud/"

[[redirects]]
from = "/think-tank/manifeste/"
to = "/manifeste/"

[[redirects]]
from = "/ouvrages/"
to = "/livres/"

[[redirects]]
from = "/technorealistes/malek-mammar/"
to = "/think-tank/membres/malek-mammar/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/pour-une-meilleure-description-de-lia/les-programmes-dia-dans-le-cadre-de-processus-metier/"
to = "/manifeste/description-ia/ia-programme/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/lia-comme-algorithme/"
to = "/manifeste/mode-ia/ia-algorithme/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/ia-systeme/"
to = "/manifeste/mode-ia/ia-systeme/"

[[redirects]]
from = "/editions/"
to = "/livres/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/modeles-ia/"
to = "/manifeste/mode-ia/modeles-ia/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/pour-une-meilleure-description-de-lia/"
to = "/manifeste/description-ia/"

[[redirects]]
from = "/technorealistes/nour-trabelsi/"
to = "/think-tank/membres/nour-trabelsi/"

[[redirects]]
from = "/membres/flavien-volken/"
to = "/think-tank/membres/flavien-volken/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/les-donnees-de-lia-lillusion-du-consentement/"
to = "/manifeste/mode-ia/ia-data/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/lia-comme-algorithme/"
to = "/manifeste/mode-ia/ia-algorithme/"

[[redirects]]
from = "/manifeste/meilleure-description/gestion-de-son-propre-cloud/"
to = "/manifeste/description-ia/ia-cloud/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/lia-et-la-decision-lillusion-de-la-raison/"
to = "/manifeste/mode-ia/ia-decision/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/lia-comme-algorithme/"
to = "/manifeste/mode-ia/ia-algorithme/"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/algorithme/"
to = "/manifeste/mode-ia/ia-algorithme/"

[[redirects]]
from = "/membres/maxime-derian/"
to = "/think-tank/membres/maxime-derian/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/pour-une-meilleure-description-de-lia/la-retention-de-donnees-dans-les-programmes-dia/"
to = "/manifeste/description-ia/ia-donnee/"

[[redirects]]
from = "/manifeste/meilleure-description/ia-donnee/"
to = "/manifeste/description-ia/ia-donnee/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/ia-outil/"
to = "/manifeste/mode-ia/ia-outil/"

[[redirects]]
from = "/membres/dylan-thomas/actualites/"
to = "/think-tank/membres/dylan-thomas/articles/"

[[redirects]]
from = "/technorealistes/arnaud-billion/"
to = "/think-tank/membres/arnaud-billion/"

[[redirects]]
from = "/agenda/2024/premiere-journee-d-etude/"
to = "/agenda/2024/journee-etudes-01/"

[[redirects]]
from = "/membres/malek-mammar/"
to = "/think-tank/membres/malek-mammar/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/ia-algorithme/"
to = "/manifeste/mode-ia/ia-algorithme/"

[[redirects]]
from = "/equipe/antoine-moreau/"
to = "/think-tank/membres/antoine-moreau/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/ia-autonome/"
to = "/manifeste/mode-ia/ia-autonome/"

[[redirects]]
from = "/actualites/"
to = "/articles/"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/donnees/"
to = "/manifeste/mode-ia/ia-data/"

[[redirects]]
from = "/manifeste/meilleure-description/ia-cloud/"
to = "/manifeste/description-ia/ia-cloud/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/equipe-editoriale/"
to = "/equipe-editoriale/"

[[redirects]]
from = "/membres/imane-idrissi/"
to = "/think-tank/membres/imane-idrissi/"

[[redirects]]
from = "/manifeste/meilleure-description/retention-de-donnees/"
to = "/manifeste/description-ia/ia-donnee/"

[[redirects]]
from = "/equipe/nour-trabelsi/"
to = "/think-tank/membres/nour-trabelsi/"

[[redirects]]
from = "/manifeste/meilleure-description/"
to = "/manifeste/description-ia/"

[[redirects]]
from = "/membres/"
to = "/think-tank/membres/"

[[redirects]]
from = "/manifeste/lubies/notions-contestables/decision/"
to = "/manifeste/mode-ia/ia-decision/"

[[redirects]]
from = "/equipe/olivier-frerot/"
to = "/think-tank/membres/olivier-frerot/"

[[redirects]]
from = "/manifeste/mode-ia/notions-contestables/ia-data/"
to = "/manifeste/mode-ia/ia-data/"

[[redirects]]
from = "/actualites/2025-05-01-ia-et-son/"
to = "/articles/2025-05-01-ia-et-son/"

[[redirects]]
from = "/manifeste/meilleure-description/frugale/"
to = "/manifeste/description-ia/ia-energie/"

[[redirects]]
from = "/manifeste/pour-une-meilleure-description-de-lia/"
to = "/manifeste/description-ia/"

[[redirects]]
from = "/equipe/maxime-derian/"
to = "/think-tank/membres/maxime-derian/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/introduction/"
to = "/think-tank/technorealisme/"

[[redirects]]
from = "/manifeste/pour-une-ia-de-qualite/"
to = "/manifeste/ia-qualite/"

[[redirects]]
from = "/technorealisme/"
to = "/think-tank/technorealisme/"

[[redirects]]
from = "/technorealistes/dylan-thomas/discussions/"
to = "/think-tank/membres/dylan-thomas/articles/"

[[redirects]]
from = "/membres/henri-albert/"
to = "/think-tank/membres/henri-albert/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/pour-une-meilleure-description-de-lia/la-gestion-par-lia-de-son-propre-cloud/"
to = "/manifeste/description-ia/ia-cloud/"

[[redirects]]
from = "/agenda/2025/beizh-data-day-2025/"
to = "/agenda/2025/breizh-data-day-2025/"

[[redirects]]
from = "/equipe/arnaud-levy/"
to = "/think-tank/membres/arnaud-levy/"

[[redirects]]
from = "/manifeste/introduction/"
to = "/think-tank/technorealisme/"

[[redirects]]
from = "/manifeste/meilleure-description/retention-donnees/"
to = "/manifeste/description-ia/ia-donnee/"

[[redirects]]
from = "/discussions/2024-03-08-sans-titre/"
to = "/articles/2024-03-08-collection-imaginaires/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/pour-une-meilleure-description-de-lia/lecriture-par-lia-de-son-propre-code/"
to = "/manifeste/description-ia/ia-code/"

[[redirects]]
from = "/agenda/2024/1ere-journee-de-technorealisme/"
to = "/agenda/2024/journee-etudes-01/"

[[redirects]]
from = "/manifeste/vers-une-ia-de-qualite/"
to = "/manifeste/ia-qualite/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/"
to = "/manifeste/"

[[redirects]]
from = "/projets/2024-lettres-de-la-machine-manuel-entree-sortie-ia/"
to = "/livres/2024-lettres-de-la-machine-manuel-entree-sortie-ia/"

[[redirects]]
from = "/technorealistes/henri-albert/"
to = "/think-tank/membres/henri-albert/"

[[redirects]]
from = "/membres/anaelle-martin/"
to = "/think-tank/membres/anaelle-martin/"

[[redirects]]
from = "/membres/christelle-serou/"
to = "/think-tank/membres/christelle-serou/"

[[redirects]]
from = "/membres/dylan-thomas/"
to = "/think-tank/membres/dylan-thomas/"

[[redirects]]
from = "/equipe/"
to = "/think-tank/membres/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/dix-lecons-sur-lia-a-lusage-des-honnetes-gens/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/manifeste/dix-lecons-sur-lia-a-lusage-des-honnetes-gens/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/membres/olivier-frerot/"
to = "/think-tank/membres/olivier-frerot/"

[[redirects]]
from = "/equipe/imane-idrissi/"
to = "/think-tank/membres/imane-idrissi/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/lia-comme-systeme-lillusion-de-cloisonnement/"
to = "/manifeste/mode-ia/ia-systeme/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/equipe-editoriale/"

[[redirects]]
from = "/dix-lecons-sur-lia-a-lusage-des-honnetes-gens/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/discussions/2024-03-08-collection-imaginaire/"
to = "/articles/2024-03-08-collection-imaginaires/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/a-lencontre-de-quelques-lubies-dominantes-sur-lia/des-notions-contestables-inutiles-voire-trompeuses/lia-autonome-et-automatique-lillusion-du-vivant/"
to = "/manifeste/mode-ia/ia-autonome/"

[[redirects]]
from = "/technorealistes/imane-idrissi/"
to = "/think-tank/membres/imane-idrissi/"

[[redirects]]
from = "/think-tank/membres/patrice-lazareff/actualites/"
to = "/think-tank/membres/patrice-lazareff/articles/"

[[redirects]]
from = "/projets/"
to = "/livres/"

[[redirects]]
from = "/technorealistes/flavien-volken/"
to = "/think-tank/membres/flavien-volken/"

[[redirects]]
from = "/technorealistes/maxime-derian/"
to = "/think-tank/membres/maxime-derian/"

[[redirects]]
from = "/equipe/dylan-thomas/discussions/"
to = "/think-tank/membres/dylan-thomas/articles/"

[[redirects]]
from = "/discussions/2024-03-08-mirage-numerique/"
to = "/articles/2024-03-08-collection-imaginaires/"

[[redirects]]
from = "/technorealistes/christelle-serou/"
to = "/think-tank/membres/christelle-serou/"

[[redirects]]
from = "/actualites/2024-03-08-collection-imaginaires/"
to = "/articles/2024-03-08-collection-imaginaires/"

[[redirects]]
from = "/equipe/henri-albert/"
to = "/think-tank/membres/henri-albert/"

[[redirects]]
from = "/technorealistes/anaelle-martin/"
to = "/think-tank/membres/anaelle-martin/"

[[redirects]]
from = "/manifeste-technorealiste-sur-lia/introduction/dix-lecons-sur-lia-a-lusage-des-honnetes-gens/"
to = "/manifeste/ia-dix-lecons/"

[[redirects]]
from = "/discussions/"
to = "/articles/"

